### ISSUE TITLE
Add license file (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/n3m0#3]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### n3m0

<img src="https://raw.githubusercontent.com/DAVFoundation/n3m0/master/20170615_155019-crop.jpg" align="right" width="240">

n3m0 is an autonomous boat being built as a collaboration between the California Maritime University, and the DAV Foundation. This project contains the code running onboard the boat's Raspberry Pi payload computer.

## How you can help

Your task for this issue is to...
Add a `LICENSE` file at the root of the project. All the DAV projects are opensource with MIT license. You can have a look at other DAV projects for its contents.

### Contributing to n3m0

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [n3m0 GitHub page](https://github.com/DAVFoundation/n3m0) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/n3m0.git`
- [ ] **Make changes in the Readme.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/n3m0](https://github.com/YOUR-USER-NAME/n3m0)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by verhaghe-benoit** [comment]
Hello @cg-cnu ,  I'm beginner and I would like to contribute for my first time.
Are you asking to create LICENSE file with MIT license ?

**Comment by cg-cnu** [comment]
Yes, you need to create a file with the name `LICENSE` at the root of the project(not LICENCE, to maintain consistency with other projects) and the contents you can get it from [here](https://github.com/DAVFoundation/missions/blob/master/LICENSE)

**Comment by verhaghe-benoit** [comment]
Ok, I'm taking this issue if there is no problem  :) !

**Comment by cg-cnu** [comment]
@verhaghe-benoit Its yours, I added the claimed tag 😄

**Comment by cg-cnu** [comment]
Thanks for your work @verhaghe-benoit 👏 Hope this is the first of many awesome contributions! 🙂 
Feel free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors)

**Comment by verhaghe-benoit** [comment]
Thanks a lot, I'll check it out !
