### ISSUE TITLE
Add gitter badge to readme (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/n3m0#4]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### n3m0

<img src="https://raw.githubusercontent.com/DAVFoundation/n3m0/master/20170615_155019-crop.jpg" align="right" width="240">

n3m0 is an autonomous boat being built as a collaboration between the California Maritime University, and the DAV Foundation. This project contains the code running onboard the boat's Raspberry Pi payload computer.

## How you can help

Your task for this issue is...
In the [README.md](https://github.com/DAVFoundation/n3m0/blob/master/README.md) file add the following line of code 

````markdown
[![Gitter](https://img.shields.io/gitter/room/DAVFoundation/DAV-Contributors.svg?style=flat-square)](https://gitter.im/DAVFoundation/DAV-Contributors)
````

This will display a badge like this [![Gitter](https://img.shields.io/gitter/room/DAVFoundation/DAV-Contributors.svg?style=flat-square)](https://gitter.im/DAVFoundation/DAV-Contributors)

Have a look at the readme.md pages of other DAV projects for location of the badge.

### Contributing to n3m0

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [n3m0 GitHub page](https://github.com/DAVFoundation/n3m0) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/n3m0.git`
- [ ] **Make changes in the Readme.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/n3m0](https://github.com/YOUR-USER-NAME/n3m0)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by vedisquori** [comment]
Hi, i'm a first timer. I would like to do this job (adding gitter badge), if it's possible ? Thanks

**Comment by cg-cnu** [comment]
Hey @TheoCouture Go ahead 👍

**Comment by cg-cnu** [comment]
Thanks for your contribution @TheoCouture Hope you had fun contributing and learned few things along the way! Feel free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors) to know about more opportunities to contribute to opensource 🙂
